name: Auto PR + Notification

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "PR: ${{ github.ref_name }}"
          body: "PR créée automatiquement"

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Nouvelle PR à valider
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions
          body: |
            Une PR a été créée.

            Branche: ${{ github.ref_name }}

            URL:
            ${{ steps.cpr.outputs.pull-request-url }}